[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "keyfile.toml"

[anki]
source = "github"
github = "ankitects/anki"
use_latest_release = true

[direnv]
source = "github"
github = "direnv/direnv"
use_latest_release = true
prefix = "v"

[lightdm-slick-greeter]
source = "github"
github = "linuxmint/slick-greeter"
use_latest_release = true
use_latest_tag = true

[lf]
source = "github"
github = "gokcehan/lf"
use_latest_release = true
prefix = "r"

[sioyek]
source = "github"
github = "ahrm/sioyek"
use_latest_release = true
prefix = "v"
